# Generated by Django 4.1.1 on 2022-10-07 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 19, 21, 50, 475329)),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 19, 21, 50, 474495)),
        ),
    ]
